import { PrismaClient } from '@prisma/client';
import { requireId } from './helpers.js';

type OpportunityRow = {
  externalId: string;
  customerExternalId: string;
  name: string;
  stage: 'PROSPECTING' | 'QUALIFIED' | 'PROPOSAL' | 'NEGOTIATION' | 'CLOSED_WON' | 'CLOSED_LOST';
  amount: string;
  probability: number;
  expectedClose: string;
};

const opportunities: OpportunityRow[] = [
  {
    externalId: 'opp-atlas-dw',
    customerExternalId: 'cust-atlas',
    name: 'Data Warehouse Modernization',
    stage: 'CLOSED_WON',
    amount: '95000.00',
    probability: 100,
    expectedClose: '2024-03-15',
  },
  {
    externalId: 'opp-atlas-mobile',
    customerExternalId: 'cust-atlas',
    name: 'Mobile Analytics Suite',
    stage: 'CLOSED_WON',
    amount: '55000.00',
    probability: 100,
    expectedClose: '2024-09-30',
  },
  {
    externalId: 'opp-atlas-ai',
    customerExternalId: 'cust-atlas',
    name: 'AI Delivery Expansion',
    stage: 'NEGOTIATION',
    amount: '64000.00',
    probability: 75,
    expectedClose: '2026-07-20',
  },
  {
    externalId: 'opp-atlas-esg',
    customerExternalId: 'cust-atlas',
    name: 'ESG Reporting Module',
    stage: 'CLOSED_WON',
    amount: '42000.00',
    probability: 100,
    expectedClose: '2025-06-01',
  },
  {
    externalId: 'opp-nova-ops',
    customerExternalId: 'cust-nova',
    name: 'Operations Analytics',
    stage: 'PROPOSAL',
    amount: '38000.00',
    probability: 55,
    expectedClose: '2026-08-05',
  },
  {
    externalId: 'opp-nova-route',
    customerExternalId: 'cust-nova',
    name: 'Route Optimization Engine',
    stage: 'CLOSED_WON',
    amount: '45000.00',
    probability: 100,
    expectedClose: '2024-07-20',
  },
  {
    externalId: 'opp-nova-fleet',
    customerExternalId: 'cust-nova',
    name: 'Fleet Telematics Platform',
    stage: 'CLOSED_LOST',
    amount: '72000.00',
    probability: 0,
    expectedClose: '2025-11-15',
  },
  {
    externalId: 'opp-pulse-risk',
    customerExternalId: 'cust-pulse',
    name: 'Risk Forecasting',
    stage: 'QUALIFIED',
    amount: '52000.00',
    probability: 45,
    expectedClose: '2026-08-28',
  },
  {
    externalId: 'opp-pulse-ehr',
    customerExternalId: 'cust-pulse',
    name: 'EHR Integration Hub',
    stage: 'CLOSED_WON',
    amount: '78000.00',
    probability: 100,
    expectedClose: '2024-11-01',
  },
  {
    externalId: 'opp-pulse-compliance',
    customerExternalId: 'cust-pulse',
    name: 'Compliance Automation',
    stage: 'CLOSED_WON',
    amount: '35000.00',
    probability: 100,
    expectedClose: '2025-05-15',
  },
  {
    externalId: 'opp-zenith-core',
    customerExternalId: 'cust-zenith',
    name: 'Core Banking Analytics',
    stage: 'CLOSED_WON',
    amount: '120000.00',
    probability: 100,
    expectedClose: '2024-06-30',
  },
  {
    externalId: 'opp-zenith-fraud',
    customerExternalId: 'cust-zenith',
    name: 'Fraud Detection Upgrade',
    stage: 'CLOSED_LOST',
    amount: '88000.00',
    probability: 0,
    expectedClose: '2026-01-20',
  },
  {
    externalId: 'opp-cobalt-scale',
    customerExternalId: 'cust-cobalt',
    name: 'Scaling Infrastructure',
    stage: 'CLOSED_WON',
    amount: '38000.00',
    probability: 100,
    expectedClose: '2024-08-10',
  },
  {
    externalId: 'opp-cobalt-retainer',
    customerExternalId: 'cust-cobalt',
    name: 'Retention Retainer',
    stage: 'PROSPECTING',
    amount: '18000.00',
    probability: 25,
    expectedClose: '2026-09-12',
  },
  {
    externalId: 'opp-cobalt-devops',
    customerExternalId: 'cust-cobalt',
    name: 'DevOps Automation',
    stage: 'CLOSED_WON',
    amount: '28000.00',
    probability: 100,
    expectedClose: '2025-04-01',
  },
  {
    externalId: 'opp-cobalt-ai',
    customerExternalId: 'cust-cobalt',
    name: 'AI-Powered Recommendations',
    stage: 'CLOSED_WON',
    amount: '52000.00',
    probability: 100,
    expectedClose: '2026-02-28',
  },
  {
    externalId: 'opp-meridian-core',
    customerExternalId: 'cust-meridian',
    name: 'Executive Risk Dashboard',
    stage: 'CLOSED_WON',
    amount: '145000.00',
    probability: 100,
    expectedClose: '2024-05-15',
  },
  {
    externalId: 'opp-meridian-aml',
    customerExternalId: 'cust-meridian',
    name: 'AML Compliance Analytics',
    stage: 'NEGOTIATION',
    amount: '98000.00',
    probability: 70,
    expectedClose: '2026-09-01',
  },
  {
    externalId: 'opp-apex-erp',
    customerExternalId: 'cust-apex',
    name: 'ERP Integration',
    stage: 'QUALIFIED',
    amount: '35000.00',
    probability: 40,
    expectedClose: '2026-10-15',
  },
  {
    externalId: 'opp-solara-grid',
    customerExternalId: 'cust-solara',
    name: 'Grid Analytics Platform',
    stage: 'CLOSED_WON',
    amount: '68000.00',
    probability: 100,
    expectedClose: '2025-03-20',
  },
  {
    externalId: 'opp-solara-carbon',
    customerExternalId: 'cust-solara',
    name: 'Carbon Reporting Suite',
    stage: 'PROPOSAL',
    amount: '45000.00',
    probability: 60,
    expectedClose: '2026-08-30',
  },
  {
    externalId: 'opp-dovetail-claims',
    customerExternalId: 'cust-dovetail',
    name: 'Claims Analytics Platform',
    stage: 'CLOSED_WON',
    amount: '82000.00',
    probability: 100,
    expectedClose: '2024-10-01',
  },
  {
    externalId: 'opp-dovetail-underwrite',
    customerExternalId: 'cust-dovetail',
    name: 'Underwriting AI Assistant',
    stage: 'PROPOSAL',
    amount: '65000.00',
    probability: 50,
    expectedClose: '2026-10-01',
  },
  {
    externalId: 'opp-prism-lms',
    customerExternalId: 'cust-prism',
    name: 'LMS Analytics Connector',
    stage: 'CLOSED_WON',
    amount: '15000.00',
    probability: 100,
    expectedClose: '2024-12-01',
  },
  {
    externalId: 'opp-riverbend-billing',
    customerExternalId: 'cust-riverbend',
    name: 'Automated Billing System',
    stage: 'CLOSED_WON',
    amount: '32000.00',
    probability: 100,
    expectedClose: '2024-09-15',
  },
  {
    externalId: 'opp-riverbend-crm',
    customerExternalId: 'cust-riverbend',
    name: 'CRM Analytics Upgrade',
    stage: 'PROSPECTING',
    amount: '22000.00',
    probability: 20,
    expectedClose: '2026-11-01',
  },
  {
    externalId: 'opp-vantage-content',
    customerExternalId: 'cust-vantage',
    name: 'Content Performance Analytics',
    stage: 'CLOSED_WON',
    amount: '36000.00',
    probability: 100,
    expectedClose: '2024-08-01',
  },
  {
    externalId: 'opp-northline-pipeline',
    customerExternalId: 'cust-northline',
    name: 'Patient Data Pipeline',
    stage: 'CLOSED_WON',
    amount: '48000.00',
    probability: 100,
    expectedClose: '2025-08-15',
  },
  {
    externalId: 'opp-northline-hipaa',
    customerExternalId: 'cust-northline',
    name: 'HIPAA Compliance Module',
    stage: 'QUALIFIED',
    amount: '28000.00',
    probability: 35,
    expectedClose: '2026-09-30',
  },
];

export async function seedSalesOpportunities(
  prisma: PrismaClient,
  customerByExternalId: Map<string, string>,
): Promise<void> {
  for (const opp of opportunities) {
    const customerId = requireId(customerByExternalId, opp.customerExternalId);

    await prisma.salesOpportunity.upsert({
      where: { externalId: opp.externalId },
      update: {
        customerId,
        name: opp.name,
        stage: opp.stage,
        amount: opp.amount,
        probability: opp.probability,
        expectedClose: new Date(opp.expectedClose),
      },
      create: {
        externalId: opp.externalId,
        customerId,
        name: opp.name,
        stage: opp.stage,
        amount: opp.amount,
        probability: opp.probability,
        expectedClose: new Date(opp.expectedClose),
      },
    });
  }
}
